name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Git identity
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Setup .NET 9 (preview)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        include-prerelease: true

    - name: Publish Blazor WebAssembly App (self-contained)
      run: dotnet publish Luigi-s-Pizza-WebApp.csproj -c Release -o release --runtime browser-wasm --self-contained true

    - name: Add .nojekyll
      run: touch release/wwwroot/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: release/wwwroot

  verify-deployment:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
    - name: Wait for GitHub Pages to propagate
      run: sleep 30

    - name: Check if site is live
      run: |
        curl -sSf https://skwwe.github.io/Luigi-s-Pizza-WebApp/ > /dev/null
        echo "✅ Main page loaded successfully."

    - name: Check if dotnet.native.wasm is accessible
      run: |
        curl -sSf https://skwwe.github.io/Luigi-s-Pizza-WebApp/_framework/dotnet.native.wasm > /dev/null
        echo "✅ dotnet.native.wasm loaded successfully."
